site_name: My Docs
site_name: Embedded C for Arm Cortex-M Microcontrollers
repo_url: https://github.com/mcusuperuser/embedded_c
nav:
    - Home: index.md
    - 'Comments': 05.md
    - 'Variables, identifiers and data types': 10.md
    - 'Constants and literals': 15.md
    - 'The printf() C library function': 20.md
    - 'Operators': 25.md
    - 'Expressions and statements': 30.md
    - 'Decision making': 35.md
    - 'Loops': 40.md
    - 'Functions': 45.md
    - 'Storage classes': 50.md
    - 'Arrays': 55.md
    - 'Pointers': 60.md
    - 'Function pointers': 65.md
    - 'Structures': 70.md
    - 'Bit fields': 75.md
    - 'Peripheral access using CMSIS': 80.md
    - 'Unions': 85.md
    - 'Enumerations': 90.md
    - 'Macros': 95.md
theme: readthedocs
use_directory_urls: false