site_name: My Docs
site_name: Embedded C for Arm Cortex-M Microcontrollers
repo_url: https://github.com/mcusuperuser/embedded_c
nav:
    - Home: index.md
    - 'Comments': comments.md
    - 'Variables, identifiers and data types': variables.md
    - 'Constants and literals': constants.md
    - 'The printf() C library function': printf.md
    - 'Operators': operators.md
    - 'Expressions and statements': expressions.md
    - 'Decision making': making_decisions.md
    - 'Loops': loops.md
    - 'Functions': functions.md
    - 'Storage classes': storage_classes.md
    - 'Arrays': arrays.md
    - 'Pointers': pointers.md
    - 'Function pointers': function_pointers.md
    - 'Structures': structures.md
    - 'Bit fields': bit_fields.md
    - 'Peripheral access using CMSIS': peripheral_access.md
    - 'Unions': unions.md
    - 'Enumerations': enums.md
    - 'Macros': macros.md
    - 'Further reading': further_reading.md
theme: readthedocs
use_directory_urls: false
markdown_extensions:
    - toc:
        permalink: "#"